development:
  adapter: postgresql
  pool: 50
  encoding: unicode
  database: my_application_development
  host: localhost
  username: volodia
  password: leobit@1

test:
  adapter: postgresql
  encoding: unicode
  database: my_application_test
  pool: 5
  host: localhost
  username: volodia
  password: leobit@1

production:
  adapter: postgresql
  encoding: unicode
  database: production
  pool: 5
